# Generated by Django 3.2.3 on 2022-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vrifylogin',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('upass', models.CharField(max_length=100)),
                ('ukey', models.CharField(max_length=100)),
            ],
        ),
    ]
